### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by User3254548** [marhau-dev/Soundpad-cracked#1]
please elabourate

**Comment by archive94-412shoes** [comment]
yes. this is safe. verified it using a windows 11 VM, it does NOT install a virus or malware. it's a true one.

**Comment by EchoVrHacks** [comment]
> yes. this is safe. verified it using a windows 11 VM, it does NOT install a virus or malware. it's a true one.

So kinda the same as on cs.rin?

**Comment by marhau-dev** [comment]
yes it safe i use it in my own pc. Да программа безопасная я использую на своём пк. Так программа безпечна використовую на свому пк.
